version: '3'
services:
  store-api:
    build:
      context: .
      args:
        NODE_ENV: docker-dev
    volumes:
      - ./:/store-api
      - store-api-node_modules:/store-api/node_modules
    environment:
      - NODE_ENV=docker-dev
    command: npm run docker-dev
volumes:
  store-api-node_modules:
    driver: local